#服务器设置
server:
  #端口设置
  port: 8080
spring:
  application:
    #当前服务名称
    name: yunztx_zuul
eureka:
  client:
    service-url:
      defaultZoon: http://127.0.0.1:10086/eureka
  instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
zuul:
  # 添加路由前缀
  prefix: /api
  retryable: true
  routes:
      item-service: /item/** # 将商品微服务映射到/item/**
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
