#服务器设置
server:
  #端口设置
  port: 4399

spring:
  application:
    #当前服务名称
    name: yunztx-zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
          #将IP注册到Eureka Server
          prefer-ip-address: true
          ip-address: 127.0.0.1
          instance-id: ${spring.application.name}:${server.port}

zuul:
  # 添加路由前缀
  prefix: /api
  retryable: true
  routes:
    #将商品微服务映射到/item/**
    item-service: /item/**